### ISSUE TITLE
与WIN10输入法不太兼容

### ISSUE THREAD

**Issue by sixrui** [majorworld/Pet#12]
WIN10，自带输入法，开启Pet后，原先打字时敲空格是确定输入内容，现在敲空格大概率无响应，需要多次敲空格，才能打出字。

**Comment by majorworld** [comment]
这个问题已经修复，还没来得及发布，新版本Space触发器后的所有按键都做成用户自定义的了，正在测试中，发布后将在这里通知你，非常感谢你的反馈。

**Comment by majorworld** [comment]
【全新升级】Pet 2.0已经发布，所有热键都可以通过Pet.ini配置文件来修改和重新绑定，快速打字空格失灵的Bug也已经彻底修复，如果你需要的话，可以重新下载体验。

快速打字空格容易失灵的情况已经彻底修复，期待您更多的反馈和建议。
