### ISSUE TITLE
窗口置顶后希望有个透明度的设置

### ISSUE THREAD

**Issue by jiangnan101** [majorworld/Pet#13]
这样工作看视频两不误了

**Comment by majorworld** [comment]
收到，现在添加，我一直以为这个功能很少有人需要，既然有人提了，人群中占比肯定不少，发布版本后我将在这里通知你，谢谢你的反馈。

**Comment by majorworld** [comment]
【全新升级】Pet 2.0已经发布，所有热键都可以通过Pet.ini配置文件来修改和重新绑定，快速打字空格失灵的Bug也已经彻底修复，如果你需要的话，可以重新下载体验。

您的需求已经实现，默认【CapsLock+F2】就是增强透明度，【CapsLock+F1】是减弱透明度，你也可以通过Pet.ini文件来重新绑定按键。

**Comment by jiangnan101** [comment]
给力
