### ISSUE TITLE
切换输入语言快捷键冲突

### ISSUE THREAD

**Issue by Gugufly** [majorworld/Pet#2]
哥啊Win+Space是切换输入语言的快捷键啊

**Comment by majorworld** [comment]
是Ctrl+Space吧，Win+Space不是Windows自带的快捷键之一，谢谢你的反馈。

**Comment by Gugufly** [comment]
Win+Space真的是win10的快捷键啊...你按一下试试...

**Comment by majorworld** [comment]
对不起，确实是切换输入法的，也是系统自带的快捷键。我一直只有一个输入法，所以按Win+Space没有任何反应，刚刚添加了一个输入法才发现效果。
建议用Ctrl+Shift切换输入法，我后期也许会修改这个快捷键。
非常抱歉，不知道这种系统快捷键。

**Comment by majorworld** [comment]
考虑到系统快捷键优先级最高，已经将增强模式的全局快捷键从Win+Space修改为Win+CapsLock，你需要的话可以重新下载。

**Comment by Gugufly** [comment]
感谢！！

**Comment by majorworld** [comment]
全新升级Pet 2.0已经发布，所有热键都可以通过Pet.ini配置文件来修改和重新绑定，快速打字空格失灵的Bug也已经彻底修复，如果你需要的话，可以重新下载体验。
