### ISSUE TITLE
符号自动补全功能

### ISSUE THREAD

**Issue by jiangnan101** [majorworld/Pet#26]
可不可以实现符号自动补全功能，例如输入“ 和（就自动输出”“和（）

**Comment by jiangnan101** [comment]
同时光标在补全的符号中间

**Comment by majorworld** [comment]
你好，这个功能QQ输入法是有自带的，可以下载体验。
[截图演示](https://meta.appinn.net/uploads/default/original/2X/b/b0ec2923ea7fb0c81e44f011ab7b1392e8aabebc.png)
![截图演示](https://meta.appinn.net/uploads/default/original/2X/b/b0ec2923ea7fb0c81e44f011ab7b1392e8aabebc.png)

你可以试试CapsLock里的ReplaceText方法，默认情况按【CapsLock+S】给选中的文本添加小括号，添加的内容可以在Pet.ini配置文件按需求配置，当然这个对你提的需求来说没什么帮助。

我斟酌了很久，决定还是不做输入法分内的事，容易造成Pet卡顿甚至各种冲突，感谢你的建议。

**Comment by majorworld** [comment]
QQ输入法这个好像是针对中文标点符号，也许你需要的是英文标点符号，暂时没有好的建议，非常抱歉。

**Comment by majorworld** [comment]
[截图演示](https://meta.appinn.net/uploads/default/original/2X/d/d6448f31b8330fa502ebb9525e376665bf69976e.png)
![截图演示](https://meta.appinn.net/uploads/default/original/2X/d/d6448f31b8330fa502ebb9525e376665bf69976e.png)

如果需要英文标点符号配对，在QQ输入法设置里勾选"中文状态下使用英文符号"，这样即可对英文标点符号进行配对补全。

QQ输入法切换中英文标点符号的快捷键是【Ctrl+.】，这边是我给你的建议了。

**Comment by jiangnan101** [comment]
好，谢谢
