### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by jiangnan101** [majorworld/Pet#3]
如果有页面拖拽功能就更好了

**Comment by majorworld** [comment]
【Space+;】按住不松开就相当于用按下鼠标左键不松开了，然后按JKLI是可以拖拽窗口的，如果鼠标处于窗口标题栏的话。
对于页面拖拽功能我不是很理解，可以详细描述一下吗

**Comment by jiangnan101** [comment]
可以了，之前没有成功，很赞的软件

**Comment by majorworld** [comment]
【全新升级】Pet 2.0已经发布，所有热键都可以通过Pet.ini配置文件来修改和重新绑定，快速打字空格失灵的Bug也已经彻底修复，如果你需要的话，可以重新下载体验。

按键变化了不少，需要看配置文件。
