### ISSUE TITLE
【赞】你他娘的是个天才！

### ISSUE THREAD

**Issue by mo-han** [majorworld/Pet#36]
辛苦了
但其实这个项目最值得推广的点并不在于这个工具本身
而是呼出、调用的方式
有不少所谓的“效率工具”（不乏已经发展得生态繁荣的项目），哪都好，就是仍然依赖一个需要呼出的菜单、轮盘
其实根本就是多余的，键鼠（或者单键盘就够了要什么鼠标）就是最好的呼出方式
（当然对残障人士和某些特殊场景下，键鼠不可用，那么语音、手势、眼控、脑电等等方式还是需要的）
设计得再好的菜单、轮盘，都不如肌肉记忆的组合键
至于组合键和功能如何对应？当然是用户自己最最清楚自己需要的是什么啦

**Comment by majorworld** [comment]
溢美之词。。。
