### ISSUE TITLE
Win 10 X64 简体中文 无法运行

### ISSUE THREAD

**Issue by VimWei** [majorworld/Pet#5]
Win 10 1909 X64 Pro 简体中文
提示：
此应用无法在你的电脑上运行
若要找到适用于你的电脑的版本，请咨询软件发布者。

**Comment by majorworld** [comment]
非常感谢你的反馈，我的也是Win 10 1909 64位，你应该是Win10 ARM64版吧。

目前市面上的CPU分类主要分有两大阵营，一个是intel、AMD为首的复杂指令集CPU，另一个是以IBM、ARM为首的精简指令集CPU。

ARM架构的CPU在笔记本上用的多，比普通CPU省电，Pet基于的AHK也许本身无法在ARM架构的CPU上运行，这个我暂时也解决不了，百度也查不到相关资料。

**Comment by VimWei** [comment]
我的处理器：Intel(R) Core(TM) i7-4650U CPU @1.70GHz 2.30GHz

我自己的AHK在这台笔记本上用的很好。

**Comment by majorworld** [comment]
这就很奇怪了，我两的Windows 10目前版本也是一样的，如果是64位的系统，下载Pet.exe或者Pet_32.exe都是可以运行的，你自己写的AHK也能正常运行，我的也是纯AHK写的，未解之谜。。。

**Comment by majorworld** [comment]
全新升级Pet 2.0已经发布，所有热键都可以通过Pet.ini配置文件来修改和重新绑定，快速打字空格失灵的Bug也已经彻底修复，如果你需要的话，可以重新下载体验。

同时试一试你的电脑能不能运行这个新版本的Pet，打扰了。
