### ISSUE TITLE
请维持 Help.txt 与 README.md 更新一致

### ISSUE THREAD

**Issue by GH01** [majorworld/Pet#8]
如果它们应该一致的话（除md格式外）。

**Comment by majorworld** [comment]
谢谢你的反馈，两者是要一致的，如果你本地的Help.txt和README.md不一致说明Pet已经升级，你本地的可执行文件需要重新下载获得更好的体验，自动生成的Help.txt自然会变成最新的。

目前对空格长按判断的优化已经完成，即使快速打字也几乎不受干扰了，但是需要重写所有的代码，暂时还没时间去升级。

升级后后我会在README.md第一行写上更新时间，本地帮助文件也有自己的时间，目前检查版本需要这样手动检查，可能比较麻烦。

**Comment by majorworld** [comment]
Pet 2.0已经发布，全新升级，所有热键都可以通过Pet.ini配置文件来修改和重新绑定，快速打字空格失灵的Bug也已经彻底修复，如果你需要的话，可以重新下载体验。

已经没有Help.txt帮助文件了，只有一个Pet.ini配置文件了。
